name: Lint

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    lint:
        name: Lint TS and CSS
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

            - name: Setup node env
              uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm ci --no-audit

            - name: Build for production
              run: npm run build

            - name: Run ESLint
              run: npm run lint
