name: Test

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    jest:
        name: Jest
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

            - name: Setup node env
              uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm ci --no-audit

            - name: Run tests
              run: npm run test
